wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: huggingface
    huggingface_version: 4.11.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1634503983
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      4: 3.8.11
      5: 0.12.1
      6: 4.11.2
      8:
      - 1
      - 3
      - 5
